### ISSUE TITLE
Analyzing games

### ISSUE THREAD

**Issue by Markel** [MarkelFe/metacritic-crawler#1]
I have noticed that there a problem on [analyze.py](https://github.com/MarkelFe/metacritic-crawler/blob/master/analyze.py) that it doesn't register all the games. I ran some test with only 30 games and 7 of them didn't appear in the SQL database. Further investigation is required.

**Comment by cdrani** [comment]
How are you limiting the amount of games added to the database?

**Comment by Markel** [comment]
I'm not, as far as I know. It's that I have 30 links and only 23 lines of databases appeared. Although I haven't tested it in a long time, I should double check 👀

**Comment by cdrani** [comment]
I mean when you said you tested it with 30 games. How did you test with only 30 games? Was it just changing the range of the for loop in games.py?

**Comment by Markel** [comment]
No, I simply deleted some lines from the games.jl, it wasn't the most sophisticated method of all time but I don't think it affected, because the other of the games that didn't appear was completely random.

**Comment by cdrani** [comment]
Okay. Found a way to limit number of games and pages in docs. Just tested with 200 games in the database and all 200 games were in there. WIll send a PR soon.

**Comment by Markel** [comment]
Oh, super nice! Looking forward to it! 😃

**Comment by Markel** [comment]
I have retested it and it doesn't happen anymore so I'm closing the issue. If someone has any problem I may reopen it.
