### ISSUE TITLE
missing setup.md

### ISSUE THREAD

**Issue by cdrani** [MarkelFe/metacritic-crawler#10]
`print('Hey, are you using the correct tool? Spoiler: read setup.md')`
Is the setup.md missing or are you referring to the readme?

**Comment by Markel** [comment]
I was meaning to the setup.md that line was written before any .md file. In the end I finish writing the setup.md content in the readme so yeah, I'm going to change it now!

**Comment by Markel** [comment]
Done, thank you for noticing it!
