### ISSUE TITLE
extra crawling on last games page

### ISSUE THREAD

**Issue by cdrani** [MarkelFe/metacritic-crawler#17]
On the last page there aren't 100 games, (hence next_page will return None), but currently the script ends up crawling the sidebar games as well. This includes the COMING SOON and the HIGH AND LOWS games. Quick fix is to make the css more strict:

```diff
- num_of_games_on_page = len(response.css('.product_title a::attr(href)').extract())
+ num_of_games_on_page = len(response.css('.product_wrap > .product_title a::attr(href)').extract())

- 'f': response.css('.product_title a::atrr(href)')[x].extract()`
+ 'f': response.css('.product_wrap > .product_title a::atrr(href)')[x].extract()`
```

The above changes rely #16 spider parameters. Will send a PR for this after #16 has been merged or you can do it.

**Comment by Markel** [comment]
Oh, I close it as it solved now.
