### ISSUE TITLE
scraping is authorized for the purposes of this project

### ISSUE THREAD

**Issue by cdrani** [MarkelFe/metacritic-crawler#28]
If you reference metatcritic's [robot.txt](https://www.metacritic.com/robots.txt), scraping is allowed for all the routes except for the disallowed ones. This project only scrapes accepted routes. Furthermore, the default delay can be set to 0 as most delays are reserved for huge page scrapes numbering in the thousands.

**Comment by Markel** [comment]
Yeah, I'm not a lawyer and I don't really know to which point the robots.txt is a legal piece or an authorization to scrap.

Anyway, I've been thinking for some days about reducing the read alerts (like having 8 lines of explanation at the start of the README), as Metacritic doesn't seem to bother a lot about this kind of projects.

About the delay, I decided to implement it as a way to stop something strange that happens. The page of best games appears blank, but only an specific one, the once before and the one after works, if you access from another IP (like Tor), it works, so it's not website problem. I could only figure out that it was like a soft anti-scraping method.

**Comment by Markel** [comment]
I'm going to maintain the delay for not having that strange bug, if someone wants to go without delay they have the possibility to do it, they only have to look at it. In terms of the notice, it's done! Commit 827cd44 🎉🎉
